<div class="nav navbar align-items-center justify-content-between bg-dark" style="height:4rem">
    <h4 class="m-0 text-light">Editar registro</h4>
    <h4 class="m-0 text-white"><i class="fas fa-toolbox mr-2" style="font-size:28px"></i></h4>
</div>
<div class="d-flex align-items-center justify-content-center px-1" style="min-height: 91vh">
    <div class="py-4 px-3 card" style="width:30rem">
        <form action="/update_service_providers" method="post">
            <input type="hidden" name="id_prestador_servico" value="<?=$_POST['id_prestador_servico']?>">
            <div class="label-float mt-4">    
                <input type="text" name="nome" class="form-custom form-control mt-1 bg-transparent" size="60" maxlength="60" placeholder="Nome" value="<?=$_POST['nome']?>">
                <label>Nome</label>
            </div>
            <div class="label-float mt-4">    
                <input type="text" name="cpf" id="cpf" class="form-custom form-control mt-1 bg-transparent" size="60" maxlength="14" placeholder="CPF" value="<?=$_POST['cpf']?>">
                <label>CPF</label>
            </div>
            <div class="label-float mt-4">    
                <input type="text" name="apartamento" class="form-custom form-control mt-1 bg-transparent" size="60" maxlength="5" placeholder="Apartamento" value="<?=$_POST['apartamento']?>">
                <label>Apartamento</label>
            </div>
            <label class="mt-4 mb-0" style="color: #20B2AA">Bloco</label>
            <select class="form-custom form-control m-0 p-0" name="bloco" style="border-bottom: 2px solid #20B2AA!important;">
                <option value="<?=$_POST['bloco']?>"><?=$_POST['bloco']?></option>
                <?php if($_POST['bloco'] == 'A'){?>
                    <option value="B">B</option>
                <?php } else {?>
                    <option value="A">A</option>
                <?php }?>
            </select>
            <button type="submit" class="btn btn-register text-white w-100 mt-5">Atualizar</button>   
            <a href="/service_providers" class="btn btn-danger text-white w-100 mt-2">Voltar</a>      
        </form>
    </div>
</div>