<div class="nav navbar align-items-center justify-content-between bg-dark" style="height:4rem">
    <h4 class="m-0 text-light">Excluir cadastro</h4>
    <h4 class="m-0 text-white"><i class="fas fa-toolbox mr-2" style="font-size:28px"></i></h4>
</div>
<div class="d-flex align-items-center justify-content-center px-1" style="min-height: 91vh">
    <div class="py-4 px-3 card" style="width:30rem">
        <div class="d-flex justify-content-between">
            <h5 class="text-dark font-weight-bold">Nome</h5>
            <h5 class="text-secondary font-weight-bold"><?=$_POST['nome']?></h5>
        </div>
        <?php if($_POST['uf'] == '--'){?> 
            <div class="d-flex justify-content-between mt-4">
                <h5 class="text-dark font-weight-bold">CPF</h5>
                <h5 class="text-secondary font-weight-bold"><?=$_POST['cpf']?></h5>
            </div>
        <?php } else {?>
            <div class="d-flex justify-content-between mt-4">
                <h5 class="text-dark font-weight-bold">RG</h5>
                <h5 class="text-secondary font-weight-bold"><?=$_POST['rg']?></h5>
            </div>
            <div class="d-flex justify-content-between mt-4">
                <h5 class="text-dark font-weight-bold">UF</h5>
                <h5 class="text-secondary font-weight-bold"><?=$_POST['uf']?></h5>
            </div>
        <?php } ?>
        <button type="button" class="btn btn-register text-white w-100 mt-4" data-toggle="modal" data-target="#deleteModal">Excluir</button>   
        <a href="/service_providers" class="btn btn-danger text-white w-100 mt-2">Voltar</a>      
    </div>
</div>

<!-- Modal de exclusão-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Excluir cadastro</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Atenção, ao excluir esse cadastro, todos os registros de entrada associados a esse prestador de serviço serão perdidos, deseja continuar?
            </div>
            <div class="modal-footer">
                <form action="/delete_service_provider" method="post">
                    <input type="hidden" name="id_prestador_servico" value="<?=$_POST['id_prestador_servico']?>">
                    <button type="submit" class="btn btn-info" style="width:120px">Sim</button>
                </form>
                <button type="button" class="btn btn-danger" style="width:120px" data-dismiss="modal">Não</button>
            </div>
        </div>
    </div>
</div>