<div class="nav navbar align-items-center justify-content-between bg-dark" style="height:4rem">
    <h4 class="m-0 text-light">Excluir registro</h4>
    <h4 class="m-0 text-white"><i class="fas fa-toolbox mr-2" style="font-size:28px"></i></h4>
</div>
<div class="d-flex align-items-center justify-content-center px-1" style="min-height: 91vh">
    <div class="py-4 px-3 card" style="width:30rem">
        <div class="d-flex justify-content-between">
            <h5 class="text-dark font-weight-bold">Nome</h5>
            <h5 class="text-secondary font-weight-bold"><?=$_POST['nome']?></h5>
        </div>
        <div class="d-flex justify-content-between mt-4">
            <h5 class="text-dark font-weight-bold">CPF</h5>
            <h5 class="text-secondary font-weight-bold"><?=$_POST['cpf']?></h5>
        </div>
        <div class="d-flex justify-content-between mt-4">
            <h5 class="text-dark font-weight-bold">Apartamento</h5>
            <h5 class="text-secondary font-weight-bold"><?=$_POST['apartamento']?></h5>
        </div>
        <div class="d-flex justify-content-between mt-4">
            <h5 class="text-dark font-weight-bold">Bloco</h5>
            <h5 class="text-secondary font-weight-bold"><?=$_POST['bloco']?></h5>
        </div>
        <div class="d-flex justify-content-between mt-4">
            <h5 class="text-dark font-weight-bold">Entrada</h5>
            <h5 class="text-secondary font-weight-bold"><?=date('d/m/Y H:i', strtotime($_POST['data_entrada']))?></h5>
        </div>
        <div class="d-flex justify-content-between mt-4">
            <h5 class="text-dark font-weight-bold">Saída</h5>
            <h5 class="text-secondary font-weight-bold">
                <?php if(!isset($_POST['data_saida']) || $_POST['data_saida'] == ''){
                    echo 'Nenhuma saída registrada';
                }else{
                    echo date('d/m/Y H:i', strtotime($_POST['data_saida']));
                }?>
            </h5>
        </div>
        <button type="button" class="btn btn-register text-white w-100 mt-4" data-toggle="modal" data-target="#deleteModal">Excluir</button>   
        <a href="/service_providers" class="btn btn-danger text-white w-100 mt-2">Voltar</a>      
    </div>
</div>
<!-- Modal de exclusão-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header text-center align-items-center">
            <h4 class="modal-title font-weight-bold text-secondary">Excluir registro</h4>
            <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
      <div class="modal-body">
        Você tem certeza que deseja excluir o registro de entrada de <?=$_POST['nome']?> no dia <?=date('d/m/Y', strtotime($_POST['data_entrada']))?> às <?=date('H:i', strtotime($_POST['data_entrada']))?>
      </div>
      <div class="modal-footer">
        <form action="/delete_service_providers" method="post">
            <input type="hidden" name="id_prestador_servico" value="<?=$_POST['id_prestador_servico']?>">
            <button type="submit" class="btn btn-info" style="width:120px">Sim</button>
        </form>
        <button type="button" class="btn btn-danger" style="width:120px" data-dismiss="modal">Não</button>
      </div>
    </div>
  </div>
</div>