<header id="header" class="header-adm d-flex align-items-center justify-content-between">
    <div class="d-xl-block d-none button ml-3 text-center" onclick="sidebarAdm()">
        <i class="fas fa-bars"></i>
    </div>
    <div class="d-xl-none d-block button ml-3 text-center" onclick="sidebarSecretAdm()">
        <i class="fas fa-bars"></i>
    </div>
    <div class="dropdown mr-3">
        <button class="btn btn-light btn-user border-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="text-dark">
                Olá,
            </span>
            <span class="text-secondary mr-1">
                <?= $_SESSION['nome'] ?>
            </span>
            <img width="35" height="35" src="img/users/<?=$_SESSION['imagem_usuario']?>">
        </button>
        <div class="dropdown-menu drop p-0" style="margin-right: 30px !important;" aria-labelledby="dropdownMenuButton">
            <a href="/my_profile">
                <i class="fas fa-user-alt ml-2"></i>
                <span class="ml-2">
                    Meu Perfil
                </span>
            </a>
            <hr class="m-0">
            <a href="/sign_out">
                <i class="fas fa-sign-out-alt ml-2"></i>
                <span class="ml-2">
                    Sair
                </span>
            </a>
        </div>
    </div> 
</header>
<aside id="menu-adm" class="menu-adm" style="margin-left:0px">
    <h4 class="pl-3 text-white logo">Access</h4>
    <small class="pl-3 text-white subtitle-menu-adm">Menu</small>
    <nav>
        <ul class="menu-list">
            <a class="d-block p-3 active" href="/dashboard">
                <i class="fas fa-chart-line icon"></i>
                <span>Dashboard</span>
            </a>
            <a class="d-block p-3" href="/residents">
                <i class="fas fa-building icon"></i>
                <span>Moradores</span>
            </a>
            <a class="d-block p-3" href="/visitors">
                <i class="fas fa-walking icon"></i>
                <span>Visitantes</span>
            </a>
            <a class="d-block p-3" href="/service_providers">
                <i class="fas fa-toolbox icon"></i>
                <span>Prestadores de serviços</span>
            </a>
            <a class="d-block p-3" href="/orders">
                <i class="fas fa-dolly icon"></i>
                <span>Encomendas</span>
            </a>
            <a class="d-block p-3" href="/leisure_areas">
                <i class="fas fa-gamepad icon"></i>
                <span>Áreas de lazer</span>
            </a>
        </ul>
    </nav>
</aside>
<aside id="menu-secret-adm" class="menu-secret-adm" style="margin-left:-18rem">
    <h4 class="pl-3 text-white logo">Access</h4>
    <small class="pl-3 text-white subtitle-menu-adm">Menu</small>
    <nav>
        <ul class="menu-list">
            <a class="d-block p-3 active" href="/dashboard">
                <i class="fas fa-chart-line icon"></i>
                <span>Dashboard</span>
            </a>
            <a class="d-block p-3" href="/residents">
                <i class="fas fa-building icon"></i>
                <span>Moradores</span>
            </a>
            <a class="d-block p-3" href="/visitors">
                <i class="fas fa-walking icon"></i>
                <span>Visitantes</span>
            </a>
            <a class="d-block p-3" href="/service_providers">
                <i class="fas fa-toolbox icon"></i>
                <span>Prestadores de serviços</span>
            </a>
            <a class="d-block p-3" href="/orders">
                <i class="fas fa-dolly icon"></i>
                <span>Encomendas</span>
            </a>
            <a class="d-block p-3" href="/leisure_areas">
                <i class="fas fa-gamepad icon"></i>
                <span>Áreas de lazer</span>
            </a>
        </ul>
    </nav>
</aside>
<section class="content-adm p-1" id="content">
    <div class="row m-auto">
        <!-- Gráfico anual -->  
        <div class="col-lg-9 col-md-8 p-0">
            <div class="card m-3 shadow">
                <div class="d-flex flex-row align-items-center justify-content-between p-3">
                    <h6 class="m-0 text-dark">Status de entrada geral</h6>
                    <span class="badge badge-info">Por ano</span>
                </div>
                <div class="card-body">
                    <canvas id="myChartByYear" style="height:420px;"></canvas>
                </div>
            </div>
        </div>
        <!-- Gráfico semanal -->
        <div class="col-lg-3 col-md-4 p-0">
            <div class="card m-3 shadow">
                <div class="d-flex flex-row align-items-center justify-content-between p-3">
                    <h6 class="m-0 text-dark">Status</h6>
                    <span class="badge badge-info">Por semana</span>
                </div>
                <div class="card-body">
                    <canvas id="myWeeklyChart" style="height:420px"></canvas>
                </div>
            </div>
        </div>
    </div>
    <div class="row m-auto">
        <div class="col-md-4 p-0">
            <div class="card m-3 shadow">
                <div class="no-gutters align-items-center">
                    <div class="d-flex flex-row align-items-center justify-content-between rounded-top p-2 border-bottom">
                        <h6 class="text-dark">Visitantes</h6>
                        <h6 class="badge badge-info">Hoje</h6>
                    </div>
                    <div class="d-flex flex-row align-items-center justify-content-between p-3">
                        <i class="fas fa-walking btn text-secondary icon-card"></i>
                        <h1 class="text-secondary"><?=$this->view->total_visitantes?></h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 p-0">
            <div class="card m-3 shadow">
                <div class="no-gutters align-items-center">
                    <div class="d-flex flex-row align-items-center justify-content-between rounded-top p-2 border-bottom">
                        <h6 class="text-dark d-none d-lg-inline-block">Prestadores de Serviços</h6>
                        <h6 class="text-dark d-lg-none d-inline-block">Prestadores S.</h6>
                        <h6 class="badge badge-info">Hoje</h6>
                    </div>
                    <div class="d-flex flex-row align-items-center justify-content-between p-3">
                        <i class="fas fa-toolbox btn text-secondary icon-card"></i>
                        <h1 class="text-secondary"><?=$this->view->total_prestadores_servicos?></h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 p-0">
            <div class="card m-3 shadow">
                <div class="no-gutters align-items-center">
                    <div
                        class="d-flex flex-row align-items-center justify-content-between rounded-top p-2 border-bottom">
                        <h6 class="text-dark">Encomendas</h6>
                        <h6 class="badge badge-info">Hoje</h6>
                    </div>
                    <div class="d-flex flex-row align-items-center justify-content-between p-3">
                        <i class="fas fa-dolly btn text-secondary icon-card"></i>
                        <h1 class="text-secondary"><?=$this->view->total_encomendas?></h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


