<header id="header" class="header d-flex align-items-center justify-content-between position-fixed bg-white">
    <div class="button ml-3 text-center" onclick="sidebarUser()">
        <i class="fas fa-bars"></i>
    </div>
    <div class="dropdown mr-3">
        <button class="btn btn-light btn-user border-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="text-dark">
                Olá,
            </span>
            <span class="text-secondary mr-1">
                <?= $_SESSION['nome'] ?>
            </span>
            <img width="35" height="35" src="img/users/user.png">
        </button>
        <div class="dropdown-menu drop p-0" aria-labelledby="dropdownMenuButton">
            <a href="/my_profile">
                <i class="fas fa-user-alt ml-2"></i>
                <span class="ml-2">
                    Meu Perfil
                </span>
            </a>
            <hr class="m-0">
            <a href="/sign_out">
                <i class="fas fa-sign-out-alt ml-2"></i>
                <span class="ml-2">
                    Sair
                </span>
            </a>
        </div>
    </div> 
</header>

<div class="container-fluid dashboard-gradient menu-user" id="menu-user" style="margin-left: -100%;">
    <div class="row dashboard-gradient">
        <a href="/visitors" class="col-md-6 bg-1 text-center">
            <h1 class="text-white"><i class="fas fa-walking px-2"></i>Visitantes</h1>
        </a>
        <a href="/service_providers" class="col-md-6 bg-2 text-center">
            <h1 class="text-white"><i class="fas fa-toolbox px-2"></i>Prestadores de serviços</h1>
        </a>
    </div>
    <div class="row dashboard-gradient">
        <a href="/orders" class="col-md-6 bg-3 text-center">
            <h1 class="text-white"><i class="fas fa-dolly px-2"></i>Encomendas</h1>
        </a>
        <a href="/residents" class="col-md-6 bg-4 text-center">
            <h1 class="text-white"><i class="fas fa-building px-2"></i>Moradores</h1>
        </a>
    </div>
</div>

<section class="content py-4 container-fluid" id="content">
    <ol class="breadcrumb mb-4 bg-dark justify-content-between">
        <li class="breadcrumb-item active text-light">
            <h4 class="m-0"><i class="fas fa-walking mr-3 ml-2" style="font-size:28px"></i>Visitantes</h4>
        </li>
        <button class="btn bg-transparent btn-exports px-3" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-v text-white"></i>
        </button>
        <div class="dropdown-menu drop p-0" aria-labelledby="dropdownMenuButton">
            <h6 class="p-2" style="color: #20B2AA">Exportar</h6>
            <a href="/export_visitors" class="px-2">
                <i class="far fa-file-excel"></i>
                <span class="ml-1">Para Excel</span>
            </a>
        </div>
    </ol>
    <div class="card mb-4 border-0">
        <div class="card-header text-center add" data-toggle="modal" data-target="#form-modal">
            <h5 class="m-0"><i class="fas fa-plus-circle mr-1"></i>Adicionar</h5>
        </div>
        <div class="card-body table-responsive pt-1">
            <table class="table table-bordered table-hover mb-0" id="dataTable">
                <thead class="text-center card-header text-dark"> 
                    <tr>
                        <th>Nome</th>
                        <th>CPF</th>
                        <th>Telefone</th>
                        <th>Apartamento</th>
                        <th>Bloco</th>
                        <th>Data de entrada</th>
                        <th>Hora de entrada</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    <?php foreach($this->view->visitantes as $e){?>
                        <tr>
                            <td><?=$e['nome']?></td>
                            <td><?=$e['cpf']?></td>
                            <td><?=$e['telefone']?></td>
                            <td><?=$e['apartamento']?></td>
                            <td><?=$e['bloco']?></td>
                            <td><?=$e['data'] = date('d/m/Y', strtotime($e['data_de_entrada']))?></td>
                            <td><?=$e['hora'] = date('H:i', strtotime($e['data_de_entrada']))?></td>
                            <th>                  
                                <form action="/edit_visitors" method="post" class="d-inline-block">          
                                    <input type="hidden" name="id_visitante" value="<?=$e['id_visitante']?>">
                                    <input type="hidden" name="nome" value="<?=$e['nome']?>">
                                    <input type="hidden" name="cpf" value="<?=$e['cpf']?>">
                                    <input type="hidden" name="telefone" value="<?=$e['telefone']?>">
                                    <input type="hidden" name="apartamento" value="<?=$e['apartamento']?>">
                                    <input type="hidden" name="bloco" value="<?=$e['bloco']?>">
                                    <button type="submit" class="btn btn-info btn-action">
                                        <i class="fas fa-edit"></i>
                                    </button>
                                </form>
                                <form action="/remove_visitors" method="post" class="d-inline-block"> 
                                    <input type="hidden" name="id_visitante" value="<?=$e['id_visitante']?>">
                                    <input type="hidden" name="nome" value="<?=$e['nome']?>">
                                    <input type="hidden" name="cpf" value="<?=$e['cpf']?>">
                                    <input type="hidden" name="telefone" value="<?=$e['telefone']?>">
                                    <input type="hidden" name="apartamento" value="<?=$e['apartamento']?>">
                                    <input type="hidden" name="bloco" value="<?=$e['bloco']?>">
                                    <input type="hidden" name="data_entrada" value="<?=$e['data']?>">
                                    <input type="hidden" name="hora_entrada" value="<?=$e['hora']?>">
                                    <button type="submit" class="btn btn-danger btn-action">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                </form>
                            </th>
                        </tr>
                    <?php }?>
                </tbody>
            </table>
        </div>   
    </div>
</section>

<!-- Modal de cadastro-->
<div class="modal fade " id="form-modal" tabindex="-1" role="dialog" aria-labelledby="title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border-0">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Visitantes</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="register_visitors" method="post">
                <div class="modal-body py-4">
                    <div class="card card-body border-0 pt-0">
                        <div class="label-float">
                            <input type="text" name="nome" class="form-custom form-control mt-2" size="60" placeholder="Nome" maxlength="60" required>
                            <label>Nome</label>
                        </div>
                        <div class="label-float mt-4">
                            <input type="text" name="cpf" id="cpf" class="form-custom form-control mt-2" size="60" placeholder="CPF" maxlength="14" required>
                            <label>CPF</label>
                        </div>
                        <div class="label-float mt-4">
                            <input type="text" name="telefone" id="telefone" class="form-custom form-control mt-2" size="60" placeholder="telefone" maxlength="20" required>
                            <label>Telefone</label>
                        </div>
                        <div class="label-float mt-4">
                            <input type="text" name="apartamento" class="form-custom form-control mt-2" size="60" placeholder="Apartamento" maxlength="5" required>
                            <label>Apartamento</label>
                        </div>
                        <label class="mt-4 mb-0 text-secondary">Bloco</label>
                        <select class="form-custom form-control mt-0 pt-0" name="bloco" style="border-bottom: 2px solid #20B2AA!important;">
                            <option value="A">A</option>
                            <option value="B">B</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-register w-100 text-light">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>
</div>
