<header id="header" class="header-adm d-flex align-items-center justify-content-between">
    <div class="d-xl-block d-none button ml-3 text-center" onclick="sidebarAdm()">
        <i class="fas fa-bars"></i>
    </div>
    <div class="d-xl-none d-block button ml-3 text-center" onclick="sidebarSecretAdm()">
        <i class="fas fa-bars"></i>
    </div>
    <button class="btn btn-light btn-user border-0 mr-3" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="text-dark">
            Olá,
        </span>
        <span class="text-secondary mr-1">
            <?= $_SESSION['nome'] ?>
        </span>
        <img width="35" height="35" src="img/users/<?= $_SESSION['imagem_usuario'] ?>">
    </button>
    <div class="dropdown-menu drop" aria-labelledby="dropdownMenuButton">
        <a href="/my_profile">
            <i class="fas fa-user-alt"></i>
            <span class="ml-2">
                Meu Perfil
            </span>
        </a>
        <hr class="m-0">
        <a href="/sign_out">
            <i class="fas fa-sign-out-alt"></i>
            <span class="ml-2">
                Sair
            </span>
        </a>
    </div>
</header>
<aside id="menu-adm" class="menu-adm" style="margin-left:0px">
    <h4 class="pl-3 text-white logo">Access</h4>
    <small class="pl-3 text-white subtitle-menu-adm">Menu</small>
    <nav>
        <ul class="menu-list">
            <a class="d-flex justify-content-between align-items-center p-3" href="/dashboard">
                <div>
                    <i class="fas fa-chart-line icon"></i>
                    <span>Dashboard</span>
                </div>
            </a>
            <a class="d-flex justify-content-between align-items-center p-3" href="/residents">
                <div>
                    <i class="fas fa-building icon"></i>
                    <span>Moradores</span>
                </div>
            </a>
            <a class="d-flex justify-content-between align-items-center p-3 active" href="/visitors">
                <div>
                    <i class="fas fa-walking icon"></i>
                    <span>Visitantes</span>
                </div>
            </a>
            <a class="d-flex justify-content-between align-items-center p-3" href="/service_providers">
                <div>    
                    <i class="fas fa-toolbox icon"></i>
                    <span>Prestadores de serviços</span>
                </div>
            </a>
            <a class="d-flex justify-content-between align-items-center p-3" href="/orders">
                <div>    
                    <i class="fas fa-dolly icon"></i>
                    <span>Encomendas</span>
                </div>
            </a>
            <a class="d-flex justify-content-between align-items-center p-3" href="/leisure_areas">
                <div>    
                    <i class="fas fa-gamepad icon"></i>
                    <span>Áreas de lazer</span>
                </div>
            </a>
        </ul>
    </nav>
</aside>
<aside id="menu-secret-adm" class="menu-secret-adm" style="margin-left:-18rem">
    <h4 class="pl-3 text-white logo">Access</h4>
    <small class="pl-3 text-white subtitle-menu-adm">Menu</small>
    <nav>
        <ul class="menu-list">
            <a class="d-flex justify-content-between align-items-center p-3" href="/dashboard">
                <div>
                    <i class="fas fa-chart-line icon"></i>
                    <span>Dashboard</span>
                </div>
            </a>
            <a class="d-flex justify-content-between align-items-center p-3" href="/residents">
                <div>    
                    <i class="fas fa-building icon"></i>
                    <span>Moradores</span>
                </div>
            </a>
            <a class="d-flex justify-content-between align-items-center p-3 active" href="/visitors">
                <div>
                    <i class="fas fa-walking icon"></i>
                    <span>Visitantes</span>
                </div>
            </a>
            <a class="d-flex justify-content-between align-items-center p-3" href="/service_providers">
                <div>
                    <i class="fas fa-toolbox icon"></i>
                    <span>Prestadores de serviços</span>
                </div>
            </a>
            <a class="d-flex justify-content-between align-items-center p-3" href="/orders">
                <div> 
                    <i class="fas fa-dolly icon"></i>
                    <span>Encomendas</span>
                </div>
            </a>
            <a class="d-flex justify-content-between align-items-center p-3" href="/leisure_areas">
                <div>
                    <i class="fas fa-gamepad icon"></i>
                    <span>Áreas de lazer</span>
                </div>
            </a>
        </ul>
    </nav>
</aside>
<section class="content-adm p-3" id="content">
    <ol class="breadcrumb mb-4 bg-dark justify-content-between">
        <li class="breadcrumb-item active">
            <button class="btn btn-outline-light" data-toggle="modal" data-target="#cad-modal">
                <h4 class="m-0"><i class="fas fa-walking mr-3 ml-2" style="font-size:28px"></i>Cadastar Visitante</h4>
            </button>
        </li>
        <button class="btn bg-transparent btn-exports px-3" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-ellipsis-v text-white"></i>
        </button>
        <div class="dropdown-menu drop p-0" aria-labelledby="dropdownMenuButton">
            <h6 class="p-2">Exportar</h6>
            <a href="/export_visitors" class="px-2">
                <i class="far fa-file-excel"></i>
                <span class="ml-1">Para Excel</span>
            </a>
        </div>
    </ol>
    <div class="card mb-4 border-0 shadow">
        <div class="row justify-content-between add-exit">
            <div class="card-header text-center add col-md-6" data-toggle="modal" data-target="#form-modal">
                <h5 class="m-0"><i class="fas fa-door-open text-white mr-1"></i>Registrar Entrada</h5>
            </div>
            <div class="card-header text-center exit col-md-6" data-toggle="modal" data-target="#view-modal">
                <h5 class="m-0">
                    <i class="fas fa-door-open text-white mr-1"></i>
                    Registrar Saída
                    <?php  if($this->view->total_visitantes_presentes){ ?>
                        <span class="badge badge-pill badge-danger" title="Total de visitantes presentes no condomínio"><?=$this->view->total_visitantes_presentes?></span>
                    <?php }?> 
                </h5>
            </div>
        </div>
        <div class="card-body table-responsive pt-1">
            <table class="table-bordered table-hover mb-0 display responsive nowrap" style="width:100%" id="dataTable" style="width:100%">
                <thead class="text-center card-header text-dark">
                    <tr>
                        <th>Nome</th>
                        <th>Documento</th>
                        <th>Apartamento</th>
                        <th>Bloco</th>
                        <th>Entrada</th>
                        <th>Saída</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    <?php foreach ($this->view->visitantes as $e) { ?>
                        <tr>
                            <td><?= $e['nome'] ?></td>
                            <td><?= $e['documento'] ?></td>
                            <td><?= $e['apartamento'] ?></td>
                            <td><?= $e['bloco'] ?></td>
                            <td><?= date('d/m/Y H:i', strtotime($e['data_entrada'])) ?></td>
                            <td>
                                <?php
                                if (!isset($e['data_saida'])) {
                                    echo 'Saída em aberto';
                                } else {
                                    echo date('d/m/Y H:i', strtotime($e['data_saida']));
                                }
                                ?>
                            </td>
                            <th>
                                <?php if (!isset($e['data_saida'])) { ?>
                                    <form action="/register_exit_visitors" method="post" class="d-inline-block">
                                        <input type="hidden" name="id_visitante" value="<?= $e['id_visitante'] ?>">
                                        <abbr title="Registrar saída">
                                            <button type="submit" class="btn btn-warning btn-action">
                                                <i class="fas fa-door-open text-white"></i>
                                            </button>
                                        </abbr>
                                    </form>
                                <?php } ?>


                                <form action="/edit_visitors" method="post" class="d-inline-block">
                                    <input type="hidden" name="id_visitante" value="<?= $e['id_visitante'] ?>">
                                    <input type="hidden" name="fk_id_visitante" value="<?= $e['fk_id_visitante'] ?>">
                                    <input type="hidden" name="apartamento" value="<?= $e['apartamento'] ?>">
                                    <input type="hidden" name="bloco" value="<?= $e['bloco'] ?>"> 
                                    <abbr title="Editar registro">
                                        <button type="submit" class="btn btn-info btn-action">
                                            <i class="fas fa-edit"></i>
                                        </button>
                                    </abbr>
                                </form>


                                <form action="/remove_visitors" method="post" class="d-inline-block">
                                    <input type="hidden" name="id_visitante" value="<?= $e['id_visitante'] ?>">
                                    <input type="hidden" name="nome" value="<?= $e['nome'] ?>">
                                    <input type="hidden" name="documento" value="<?= $e['documento'] ?>">
                                    <input type="hidden" name="apartamento" value="<?= $e['apartamento'] ?>">
                                    <input type="hidden" name="bloco" value="<?= $e['bloco'] ?>">
                                    <input type="hidden" name="data_entrada" value="<?= $e['data_entrada'] ?>">
                                    <input type="hidden" name="data_saida" value="<?= $e['data_saida'] ?>">
                                    <abbr title="Excluir registro">
                                        <button type="submit" class="btn btn-danger btn-action">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                    </abbr>
                                </form>
                            </th>
                        </tr>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</section>

<!-- Modal de cadastro -->
<div class="modal fade" id="cad-modal" tabindex="-1" role="dialog" aria-labelledby="title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border-0">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Cadastrar Visitante</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="register_visitors" method="post">
                <div class="modal-body py-4">
                    <div class="card card-body border-0 pt-0">
                        <div class="label-float">
                            <input type="text" name="nome" class="form-custom form-control mt-2" size="60" placeholder="Nome" maxlength="60" required>
                            <label>Nome</label>
                        </div>
                        <label class="mt-4 mb-0 text-secondary">Documento</label>
                        <select id="select-documento-cadastro" name="documento" class="form-custom form-control m-0 p-0" style="border-bottom: 2px solid #20B2AA!important;">
                            <option value="CPF">CPF</option>
                            <option value="RG">RG</option>
                        </select>
                        <div class="label-float mt-4" id="input-cpf-cadastro">
                            <input type="text" id="cad-cpf" name="cpf" class="form-custom form-control mt-2" size="60" placeholder="CPF" maxlength="14">
                            <label>CPF</label>
                            <div class="invalid-feedback" id="cad-invalid">
                                CPF inválido!
                            </div>
                        </div>
                        <label id="label-uf-cadastro" class="mt-4 mb-0 text-secondary">UF</label>
                        <select id="select-uf-cadastro" name="uf" class="form-custom form-control m-0 p-0" style="border-bottom: 2px solid #20B2AA!important;">
                            <option value="SP">SP</option> 
                            <option value="AC">AC</option>
                            <option value="AL">AL</option>
                            <option value="AM">AM</option>
                            <option value="AP">AP</option>
                            <option value="BA">BA</option>
                            <option value="CE">CE</option>
                            <option value="DF">DF</option>
                            <option value="ES">ES</option>
                            <option value="GO">GO</option>      
                            <option value="MA">MA</option>      
                            <option value="MG">MG</option>      
                            <option value="MS">MS</option>      
                            <option value="MT">MT</option>      
                            <option value="PA">PA</option>      
                            <option value="PB">PB</option>      
                            <option value="PI">PI</option>      
                            <option value="PE">PE</option>      
                            <option value="PR">PR</option>   
                            <option value="RJ">RJ</option>   
                            <option value="RN">RN</option>      
                            <option value="RO">RO</option>      
                            <option value="RR">RR</option>      
                            <option value="RS">RS</option>      
                            <option value="SC">SC</option>      
                            <option value="SE">SE</option>      
                            <option value="TO">TO</option>      
                        </select>
                        <div class="label-float mt-4" id="input-rg-cadastro">
                            <input type="text" id="cad-rg" name="rg" class="form-custom form-control mt-2" size="60" placeholder="RG">
                            <label>RG</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="registrar" class="btn btn-register w-100 text-light">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal de registro de entrada-->
<div class="modal fade" id="form-modal" tabindex="-1" role="dialog" aria-labelledby="title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border-0">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Registrar Entrada</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="register_entry_visitors" method="post">
                <div class="modal-body py-4">
                    <div class="card card-body border-0 pt-0">
                        <label class="mt-0 mb-0 text-secondary">Documento</label>
                        <select id="select-documento-registro" name="documento" class="form-custom form-control m-0 p-0" style="border-bottom: 2px solid #20B2AA!important;">
                            <option value="CPF">CPF</option>
                            <option value="RG">RG</option>
                        </select>
                        <div class="label-float mt-4" id="input-cpf-registro">
                            <input type="text" id="cpf" name="cpf" class="form-custom form-control mt-2" size="60" placeholder="CPF" maxlength="14">
                            <label>CPF</label>
                            <div class="invalid-feedback" id="invalid">
                                CPF inválido!
                            </div>
                        </div>
                        <label id="label-uf-registro" class="mt-4 mb-0 text-secondary">UF</label>
                        <select id="select-uf-registro" name="uf" class="form-custom form-control m-0 p-0" style="border-bottom: 2px solid #20B2AA!important;">
                            <option value="SP">SP</option> 
                            <option value="AC">AC</option>
                            <option value="AL">AL</option>
                            <option value="AM">AM</option>
                            <option value="AP">AP</option>
                            <option value="BA">BA</option>
                            <option value="CE">CE</option>
                            <option value="DF">DF</option>
                            <option value="ES">ES</option>
                            <option value="GO">GO</option>      
                            <option value="MA">MA</option>      
                            <option value="MG">MG</option>      
                            <option value="MS">MS</option>      
                            <option value="MT">MT</option>      
                            <option value="PA">PA</option>      
                            <option value="PB">PB</option>      
                            <option value="PI">PI</option>      
                            <option value="PE">PE</option>      
                            <option value="PR">PR</option>   
                            <option value="RJ">RJ</option>   
                            <option value="RN">RN</option>      
                            <option value="RO">RO</option>      
                            <option value="RR">RR</option>      
                            <option value="RS">RS</option>      
                            <option value="SC">SC</option>      
                            <option value="SE">SE</option>      
                            <option value="TO">TO</option>      
                        </select>
                        <div class="label-float mt-4" id="input-rg-registro">
                            <input type="text" id="rg" name="rg" class="form-custom form-control mt-2" size="60" placeholder="RG">
                            <label>RG</label>
                        </div>
                        <div class="label-float mt-4">
                            <input type="text" name="apartamento" class="form-custom form-control mt-2" size="60" placeholder="Apartamento" maxlength="5" required>
                            <label>Apartamento</label>
                        </div>
                        <label class="mt-4 mb-0 text-secondary">Bloco</label>
                        <select class="form-custom form-control m-0 p-0" name="bloco" style="border-bottom: 2px solid #20B2AA!important;">
                            <option value="A">A</option>
                            <option value="B">B</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit"  class="btn btn-register w-100 text-light">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal de visualização-->
<div class="modal fade" id="view-modal" tabindex="-1" role="dialog" aria-labelledby="title" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content border-0">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Visitantes</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="card-body table-responsive pt-1" style="overflow-x:hidden">
                <table class="display responsive nowrap table-bordered table-hover mb-0" id="dataTableModal" style="width: 100%;">
                    <thead class="text-center card-header text-dark">
                        <tr>
                            <th>Nome</th>
                            <th>Documento</th>
                            <th>Apartamento</th>
                            <th>Bloco</th>
                            <th>Entrada</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                        <?php foreach ($this->view->visitantes_presentes as $e) { ?>
                            <tr>
                                <td><?= $e['nome'] ?></td>
                                <td><?= $e['documento'] ?></td>
                                <td><?= $e['apartamento'] ?></td>
                                <td><?= $e['bloco'] ?></td>
                                <td><?= date('d/m/Y H:i', strtotime($e['data_entrada'])) ?></td>
                                <th>
                                    <form action="/register_exit_visitors" method="post" class="d-inline-block">
                                        <input type="hidden" name="id_visitante" value="<?= $e['id_visitante'] ?>">
                                        <abbr title="Registrar saída">
                                            <button type="submit" class="btn btn-warning btn-action text-white w-100">
                                                <i class="fas fa-door-open"></i>
                                                Registrar Saída
                                            </button>
                                        </abbr>
                                    </form>
                                </th>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script src="lib/datatables/js/query-3.5.1.js"></script>
<script src="lib/jquery/jquery.mask.min.js"></script>
<script src="js/mask-rg.js"></script>


<!-- Exibição dos campos RG e CPF de acordo com o documento escolhido -->
<script>
    $('#input-rg-cadastro').hide();
    $('#label-uf-cadastro').hide();
    $('#select-uf-cadastro').hide();

    $("#select-documento-cadastro").change(function() {
        if(this.value == "RG"){
            $('#input-rg-cadastro').show();
            $('#label-uf-cadastro').show();
            $('#select-uf-cadastro').show();
            $('#input-cpf-cadastro').hide()
        }
        else if(this.value == "CPF"){
            $('#input-rg-cadastro').hide();
            $('#label-uf-cadastro').hide();
            $('#select-uf-cadastro').hide();
            $('#input-cpf-cadastro').show();
        }
    });

    $('#input-rg-registro').hide();
    $('#label-uf-registro').hide();
    $('#select-uf-registro').hide();

    $("#select-documento-registro").change(function() {
        if(this.value == "RG"){
            $('#input-rg-registro').show();
            $('#label-uf-registro').show();
            $('#select-uf-registro').show();
            $('#input-cpf-registro').hide()
        }
        else if(this.value == "CPF"){
            $('#input-rg-registro').hide();
            $('#label-uf-registro').hide();
            $('#select-uf-registro').hide();
            $('#input-cpf-registro').show();
        }
    });
</script>

