<header class="row m-auto align-items-center justify-content-center bg-forgot-password">
    <section class="py-4 px-md-5 px-4 m-auto registration-panel">
        <h2 class="text-secondary text-center">Alterar senha</h2>
        <form action="/update_password" method="post">
          <div class="label-float mt-4">    
            <input type="email" name="email" class="form-custom form-control mt-1" size="60" maxlength="60" placeholder="E-mail" >
            <label>E-mail</label>
          </div>
          <div class="label-float mt-4">    
            <input type="cpf" name="cpf" id="cpf" class="form-custom form-control mt-1" size="60" maxlength="14" placeholder="CPF" >
            <label>CPF</label>
          </div>
          <div class="label-float mt-4">    
            <input type="password" name="senha" class="form-custom form-control mt-1" size="60" maxlength="15" placeholder="Senha" >
            <label>Nova senha</label>
          </div>
          <div class="label-float mt-4">    
            <input type="password" name="confirmar_senha"  class="form-custom form-control mt-1" size="60" maxlength="15" placeholder="Confrimar senha" >
            <label>Confirmar senha</label>
          </div>
          <button type="submit" class="btn btn-register text-white w-100 mt-4">Confirmar</button>
          <a href="/" class="btn btn-danger text-white w-100 mt-2">Voltar</a>
        </form>
    </section>
</header>


