<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">

        <div class="row">
          <div class="col">
            <h2 class="text-center text-dark">Cadastro realizado com sucesso</h2>
          </div>
        </div>

        <div class="row mt-3">
          <div class="col">
            <a href="/" class="btn btn-register text-white btn-block">Clique aqui para realizar o login!</a>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>



    
  