<header class="row m-auto align-items-center justify-content-center bg-register">
    <section class="py-5 px-md-5 px-4 m-auto registration-panel">
        <h2 class="text-secondary text-center">Cadastre-se</h2>
        <form action="/register" method="post">
            <div class="label-float mt-4">    
              <input type="text" name="nome" value="<?= $this->view->usuario['nome']?>" class="form-control mt-1" size="60" maxlength="60" placeholder="Nome" required>
              <label>Nome</label>
            </div>
            <div class="label-float mt-4">    
              <input type="email" name="email" value="<?= $this->view->usuario['email']?>" class="form-control mt-1" size="60" maxlength="60" placeholder="E-mail" required>
              <label>E-mail</label>
            </div>
            <div class="label-float mt-4">    
              <input type="password" name="senha" value="<?= $this->view->usuario['senha']?>" class="form-control mt-1" size="60" maxlength="15" placeholder="Senha" required>
              <label>Senha</label>
            </div>
            <div class="label-float mt-4">    
              <input type="password" name="confirmar_senha" value="<?= $this->view->usuario['confirmar_senha']?>" class="form-control mt-1" size="60" maxlength="15" placeholder="Confrimar senha" required>
              <label>Confirmar senha</label>
            </div>
            <div class="mt-4">    
              <label class="text-dark d-block">Nível de acesso</label>
              <div class="custom-control custom-radio d-inline-block mt-2">
                <input type="radio" class="custom-control-input" id="usuario" value="usuario" name="user-admin" required>
                <label class="custom-control-label text-dark" for="usuario">Usuário</label>
              </div>
              <div class="custom-control custom-radio d-inline-block mt-2 ml-3">
                <input type="radio" class="custom-control-input" id="administrador" value="administrador" name="user-admin" required>
                <label class="custom-control-label text-dark" for="administrador">Administrador</label>
              </div>
            </div>
            <button type="submit" class="btn btn-register text-white w-100 mt-4">Cadastrar</button>

            <?php if(empty($this->view->erroCadastroDados)){ ?>
            <?php } else if($this->view->erroCadastroDados == 1){ ?>
                  <small class="form-text text-danger">Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.</small>
            <?php } else if($this->view->erroCadastroDados == 2){ ?>
                  <small class="form-text text-danger">As senhas não correspondem, digite senhas iguais.</small>
            <?php } else if($this->view->erroCadastroDados == 3){ ?>
                  <small class="form-text text-danger">Este e-mail ja está sendo utilizado, cadastre outro e-mail.</small>
            <?php } ?>

            <a href="/" class="mt-2 d-block">Ja possui cadastro? realize o login</a>
        </form>
    </section>
</header>


