<header id="" class="header d-flex align-items-center justify-content-between position-fixed">
    <div class="button ml-3 text-center" onclick="sidebarUser()">
        <i class="fas fa-bars"></i>
    </div>
    <a href="leisure_areas" class="btn btn-dark text-white ml-auto mr-1">
        <i class="fa fa-calendar" aria-hidden="true"></i>
    </a>
    <button class="btn btn-light btn-user border-0 mr-3" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="text-dark">
            Olá,
        </span>
        <span class="text-secondary mr-1">
            <?= $_SESSION['nome'] ?>
        </span>
        <img width="35" height="35" src="img/users/<?= $_SESSION['imagem_usuario'] ?>">
    </button>
    <div class="dropdown-menu drop" aria-labelledby="dropdownMenuButton">
        <a href="/my_profile">
            <i class="fas fa-user-alt"></i>
            <span class="ml-2">
                Meu Perfil
            </span>
        </a>
        <hr class="m-0">
        <a href="/sign_out">
            <i class="fas fa-sign-out-alt"></i>
            <span class="ml-2">
                Sair
            </span>
        </a>
    </div>
</header>
<div class="container-fluid dashboard-gradient menu-user mt-10vh" id="menu-user" style="margin-left: -100%;">
    <div class="row dashboard-gradient">
        <a href="/visitors" class="col-md-6 bg-1 text-center">
            <h1 class="text-white"><i class="fas fa-walking px-2"></i>Visitantes</h1>
        </a>
        <a href="/service_providers" class="col-md-6 bg-2 text-center">
            <h1 class="text-white"><i class="fas fa-toolbox px-2"></i>Prestadores de serviços</h1>
        </a>
    </div>
    <div class="row dashboard-gradient">
        <a href="/orders" class="col-md-6 bg-3 text-center">
            <h1 class="text-white"><i class="fas fa-dolly px-2"></i>Encomendas</h1>
        </a>
        <a href="/residents" class="col-md-6 bg-4 text-center">
            <h1 class="text-white"><i class="fas fa-building px-2"></i>Moradores</h1>
        </a>
    </div>
</div>
<section class="container-fluid ontent-user p-3">
    <div class="table-events ">
        <ol class="breadcrumb mb-4 bg-dark justify-content-between">
            <li class="breadcrumb-item active text-light">
                <h4 class="m-0"><i class="fa fa-calendar mr-3 ml-2" style="font-size:28px"></i>Eventos</h4>
            </li>
        </ol>
    </div>
    <div class="card mb-4 border-0 shadow p-4">
        <table class=" table-bordered table-hover mb-0 display responsive nowrap" style="width:100%" id="dataTableCad" role="tabpanel" aria-labelledby="dataTable-tab">
            <thead class="text-center card-header text-dark">
                <tr>
                    <th>Local</th>
                    <th>Inicio do vento</th>
                    <th>Fim do evento</th>
                </tr>
            </thead>
            <tbody class="text-center">
                <?php foreach ($this->view->event as $e) { ?>
                    <tr>
                        <td><?= $e['titulo_evento'] ?></td>
                        <td><?= date('d/m/Y H:i', strtotime($e['inicio_evento'])) ?></td>
                        <td><?= date('d/m/Y H:i', strtotime($e['fim_evento'])) ?></td>

                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</section>