<header id="header" class="header-adm d-flex align-items-center justify-content-between">
    <div class="d-xl-block d-none button ml-3 text-center" onclick="sidebarAdm()">
        <i class="fas fa-bars"></i>
    </div>
    <div class="d-xl-none d-block button ml-3 text-center" onclick="sidebarSecretAdm()">
        <i class="fas fa-bars"></i>
    </div>
    <div class="dropdown mr-3">
        <button class="btn btn-light btn-user border-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="text-dark">
                Olá,
            </span>
            <span class="text-secondary mr-1">
                <?= $_SESSION['nome'] ?>
            </span>
            <img width="35" height="35" src="img/users/<?=$_SESSION['imagem_usuario']?>">
        </button>
        <div class="dropdown-menu drop p-0" style="margin-right: 30px !important;" aria-labelledby="dropdownMenuButton">
            <a href="/my_profile">
                <i class="fas fa-user-alt ml-2"></i>
                <span class="ml-2">
                    Meu Perfil
                </span>
            </a>
            <hr class="m-0">
            <a href="/sign_out">
                <i class="fas fa-sign-out-alt ml-2"></i>
                <span class="ml-2">
                    Sair
                </span>
            </a>
        </div>
    </div> 
</header>
<aside id="menu-adm" class="menu-adm" style="margin-left:0px">
    <h4 class="pl-3 text-white logo">Access</h4>
    <small class="pl-3 text-white subtitle-menu-adm">Menu</small>
    <nav>
        <ul class="menu-list">
            <a class="d-block p-3" href="/dashboard">
                <i class="fas fa-chart-line icon"></i>
                <span>Dashboard</span>
            </a>
            <a class="d-block p-3" href="/residents">
                <i class="fas fa-building icon"></i>
                <span>Moradores</span>
            </a>
            <a class="d-block p-3" href="/visitors">
                <i class="fas fa-walking icon"></i>
                <span>Visitantes</span>
            </a>
            <a class="d-block p-3" href="/service_providers">
                <i class="fas fa-toolbox icon"></i>
                <span>Prestadores de serviços</span>
            </a>
            <a class="d-block p-3" href="/orders">
                <i class="fas fa-dolly icon"></i>
                <span>Encomendas</span>
            </a>
            <a class="d-block p-3 active" href="/leisure_areas">
                <i class="fas fa-gamepad icon"></i>
                <span>Áreas de lazer</span>
            </a>
        </ul>
    </nav>
</aside>
<aside id="menu-secret-adm" class="menu-secret-adm" style="margin-left:-18rem">
    <h4 class="pl-3 text-white logo">Access</h4>
    <small class="pl-3 text-white subtitle-menu-adm">Menu</small>
    <nav>
        <ul class="menu-list">
            <a class="d-block p-3" href="/dashboard">
                <i class="fas fa-chart-line icon"></i>
                <span>Dashboard</span>
            </a>
            <a class="d-block p-3" href="/residents">
                <i class="fas fa-building icon"></i>
                <span>Moradores</span>
            </a>
            <a class="d-block p-3" href="/visitors">
                <i class="fas fa-walking icon"></i>
                <span>Visitantes</span>
            </a>
            <a class="d-block p-3" href="/service_providers">
                <i class="fas fa-toolbox icon"></i>
                <span>Prestadores de serviços</span>
            </a>
            <a class="d-block p-3" href="/orders">
                <i class="fas fa-dolly icon"></i>
                <span>Encomendas</span>
            </a>
            <a class="d-block p-3 active" href="/leisure_areas">
                <i class="fas fa-gamepad icon"></i>
                <span>Áreas de lazer</span>
            </a>
        </ul>
    </nav>
</aside>
<section class="content-adm p-3" id="content">
    <div id="calendar" class="calendar shadow"></div>
</section>
<!-- Modal de cadastro-->
<div class="modal fade" id="cadastrar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content border-0">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Eventos</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="/register_event" method="post" id="addevent" enctype="multipart/form-data">
                <div class="modal-body py-4">
                    <div class="card card-body border-0 pt-0">
                        <div class="label-float">
                            <input type="text" name="nome" class="form-custom form-control mt-2" size="60" maxlength="60" placeholder="Nome" required>
                            <label>Nome</label>
                        </div>
                        <div class="label-float mt-4">
                            <input type="text" name="cpf" class="form-custom form-control mt-2" size="60" maxlength="14" id="cpf"  placeholder="CPF" required>
                            <label>CPF</label>
                        </div>
                        <div class="label-float mt-4">
                            <input type="text" name="titulo_evento" class="form-custom form-control mt-2" size="60" maxlength="60" id="title"  placeholder="Título do evento" required>
                            <label>Título do evento</label>
                        </div>
                        <div class="label-float mt-4">
                            <input type="text" name="inicio_evento" class="form-custom form-control mt-2" size="60" maxlength="60" id="start" onkeypress="DataHora(event, this)" placeholder="Início do evento" required>
                            <label>Início do evento</label>
                        </div>
                        <div class="label-float mt-4">
                            <input type="text" name="fim_evento" class="form-custom form-control mt-2" size="60" maxlength="60" id="end" onkeypress="DataHora(event, this)" placeholder="Fim do evento" required>
                            <label>Fim do evento</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-register w-100 text-light">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>
</div>




<div class="modal fade" id="visualizar" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header align-items-center">
                    <h5 class="modal-title text-dark" id="exampleModalLabel">Detalhes do Evento</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body px-0">

                    <!-- Excluindo dados -->
                    <div class="visevent">
                        <dl class="row px-3">
                            <dt class="col-sm-6">Título do evento</dt>
                            <dd class="col-sm-6" id="title"></dd>
                    
                            <dt class="col-sm-6">Início do evento</dt>
                            <dd class="col-sm-6" id="start"></dd>
                            
                            <dt class="col-sm-6">Fim do evento</dt>
                            <dd class="col-sm-6" id="end"></dd>
                        </dl>
                        <div class="modal-footer pb-0">
                            <button class="btn btn-info btn-canc-vis text-white" style="width:120px">Editar</button>
                            <form action="/delete_event" class="d-inline-block" method="post">
                                <input type="hidden" name="id" id="id" >
                                <button style="width:120px" type="submit" class="btn btn-danger">Excluir</button>
                            </form>
                        </div>
                    </div>

                    <!-- Atualizando dados -->
                    <div class="formedit">
                        <form action="/update_event" method="post" enctype="multipart/form-data">
                            <div class="modal-body px-3">
                                <input type="hidden" name="id" id="id" >
                                <div class="form-group row">
                                    <label class="col-sm-4 col-form-label">Título</label>
                                    <div class="col-sm-8">
                                        <input type="text" name="titulo" class="form-control" id="title" placeholder="Título do evento">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-4 col-form-label">Cor</label>
                                    <div class="col-sm-8">
                                        <select name="cor" class="form-control" id="color">
                                            <option value="">Selecione</option>			
                                            <option style="color:#FFD700;" value="#FFD700">Amarelo</option>
                                            <option style="color:#0071c5;" value="#0071c5">Azul Turquesa</option>
                                            <option style="color:#FF4500;" value="#FF4500">Laranja</option>
                                            <option style="color:#8B4513;" value="#8B4513">Marrom</option>	
                                            <option style="color:#1C1C1C;" value="#1C1C1C">Preto</option>
                                            <option style="color:#436EEE;" value="#436EEE">Royal Blue</option>
                                            <option style="color:#A020F0;" value="#A020F0">Roxo</option>
                                            <option style="color:#40E0D0;" value="#40E0D0">Turquesa</option>
                                            <option style="color:#228B22;" value="#228B22">Verde</option>
                                            <option style="color:#8B0000;" value="#8B0000">Vermelho</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-4 col-form-label">Início do evento</label>
                                    <div class="col-sm-8">
                                        <input type="text" name="inicio_evento" class="form-control" id="start" onkeypress="DataHora(event, this)">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-sm-4 col-form-label">Final do evento</label>
                                    <div class="col-sm-8">
                                        <input type="text" name="fim_evento" class="form-control" id="end"  onkeypress="DataHora(event, this)">
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer pb-0">           
                                <button type="submit" style="width:120px" class="btn btn-info">Atualizar</button> 
                                <button type="button" style="width:120px" class="btn btn-danger btn-canc-edit">Cancelar</button>                                  
                            </div>
                        </form>                            
                    </div>
                </div>
            </div>
        </div>
    </div>