<div class="nav navbar align-items-center justify-content-between bg-dark" style="height:4rem">
    <h4 class="m-0 text-light">Informações do evento</h4>
    <h4 class="m-0 text-white"><i class="fas fa-gamepad mr-2" style="font-size:28px"></i></h4>
</div>
<div class="d-flex align-items-center justify-content-center px-1" style="min-height: 91vh">
    <div class="py-4 px-3 card" style="width:30rem">
        <?php foreach ($this->view->eventos as $e) { ?>
            <div class="d-sm-flex d-none justify-content-between">
                <h5 class="text-dark font-weight-bold">Agendado por</h5>
                <h5 class="text-secondary font-weight-bold"><?= $e['nome'] ?></h5>
            </div>
            <div class="d-sm-none d-block">
                <h5 class="text-dark font-weight-bold">Agendado por</h5>
                <h5 class="text-secondary font-weight-bold"><?= $e['nome'] ?></h5>
            </div>
            <div class="d-flex justify-content-between mt-4">
                <h5 class="text-dark font-weight-bold">Telefone</h5>
                <h5 class="text-secondary font-weight-bold">
                    <?php if($e['telefone'] != ''){
                            echo $e['telefone'];
                        } else{
                            echo "(xx) xxxx-xxxxx";
                        }
                    ?>
                </h5>
            </div>
            <div class="d-flex justify-content-between mt-4">
                <h5 class="text-dark font-weight-bold">Apartamento</h5>
                <h5 class="text-secondary font-weight-bold"><?= $e['apartamento'] ?></h5>
            </div>
            <div class="d-flex justify-content-between mt-4">
                <h5 class="text-dark font-weight-bold">Bloco</h5>
                <h5 class="text-secondary font-weight-bold"><?= $e['bloco'] ?></h5>
            </div>
            <div class="d-flex justify-content-between mt-4">
                <h5 class="text-dark font-weight-bold">Local</h5>
                <h5 class="text-secondary font-weight-bold"><?= $e['titulo_evento'] ?></h5>
            </div>
            <div class="d-flex justify-content-between mt-4">
                <h5 class="text-dark font-weight-bold">Início do evento</h5>
                <h5 class="text-secondary font-weight-bold"><?= date("d/m/Y H:i", strtotime($e['inicio_evento'])) ?></h5>
            </div>
            <div class="d-flex justify-content-between mt-4">
                <h5 class="text-dark font-weight-bold">Fim do evento</h5>
                <h5 class="text-secondary font-weight-bold"><?= date("d/m/Y H:i", strtotime($e['fim_evento'])) ?></h5>
            </div>
        <?php } ?>
        <div class="d-flex justify-content-between">
            <button type="button" class="btn btn-dark text-white w-100 mt-4 mr-1" data-toggle="modal" data-target="#editModal">Editar</button>
            <button type="button" class="btn btn-register text-white w-100 mt-4 mr-1" data-toggle="modal" data-target="#deleteModal">Excluir</button>
            <a href="/leisure_areas" class="btn btn-danger text-white w-100 mt-4">Voltar</a>
        </div>
    </div>
</div>
<!-- Modal de edição-->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Editar evento</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="/update_event" method="post">
                <div class="modal-body py-4">
                    <div class="card card-body border-0 pt-0">
                        <input type="hidden" name="id_evento" value="<?= $e['id_evento'] ?>">
                        <div class="label-float">
                            <input type="text" name="cpf" class="form-custom form-control mt-2" size="60" maxlength="14" id="cpf" placeholder="CPF" value="<?=$e['cpf']?>">
                            <label>CPF</label>
                            <div class="invalid-feedback" id="invalid">
                                CPF inválido!
                            </div>
                        </div>
                        <label class="mt-3 mb-0 text-secondary">Local</label>
                        <select class="form-custom form-control m-0 p-0" name="titulo_evento" style="border-bottom: 2px solid #20B2AA!important;">
                            <?php if($e['titulo_evento'] == 'Salão de festas'){ ?> 
                                <option value="Salão de festas">Salão de festas</option>
                                <option value="Churrasqueira">Churrasqueira</option>
                            <?php } else { ?>
                                <option value="Churrasqueira">Churrasqueira</option>
                                <option value="Salão de festas">Salão de festas</option> 
                            <?php } ?>
                        </select>
                        <div class="label-float mt-4">
                            <input type="text" name="inicio_evento" class="form-custom form-control mt-2" size="60" maxlength="60" id="inicio_evento" onkeypress="DataHora(event, this)" placeholder="Início do evento" value="<?= date("d/m/Y H:i", strtotime($e['inicio_evento'])) ?>">
                            <label>Início do evento</label>
                        </div>
                        <div class="label-float mt-4">
                            <input type="text" name="fim_evento" class="form-custom form-control mt-2" size="60" maxlength="60" id="fim_evento" onkeypress="DataHora(event, this)" placeholder="Fim do evento" value="<?= date("d/m/Y H:i", strtotime($e['fim_evento'])) ?>">
                            <label>Fim do evento</label>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-register w-100 text-light">Atualizar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- Modal de exclusão-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header text-center align-items-center">
                <h4 class="modal-title font-weight-bold text-secondary">Excluir evento</h4>
                <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Você tem certeza que deseja excluir esse evento?
            </div>
            <div class="modal-footer">
                <form action="/delete_event" method="post">
                    <input type="hidden" name="id_evento" value="<?= $e['id_evento'] ?>">
                    <button type="submit" class="btn btn-info" style="width:120px">Sim</button>
                </form>
                <button type="button" class="btn btn-danger" style="width:120px" data-dismiss="modal">Não</button>
            </div>
        </div>
    </div>
</div>

<script src="lib/datatables/js/query-3.5.1.js"></script>
<script src="lib/jquery/jquery.mask.min.js"></script>

<script>
    $("#inicio_evento").mask("99/99/9999 99:99:99");
    $("#fim_evento").mask("99/99/9999 99:99:99");
</script>