<div class="nav navbar align-items-center bg-dark" style="height:8vh">
    <h5 class="m-0 text-light">Atualizar cadastro</h5>
</div>

<div class="d-flex align-items-center justify-content-center px-1" style="height:92vh">

    <div class="py-4 px-3 card" style="width:30rem">
        <form action="/update_orders" method="post">
            <input type="hidden" name="id_encomenda" value="<?=$_POST['id_encomenda']?>">
            <div class="label-float mt-4">    
                <input type="text" name="empresa" class="form-control mt-1 bg-transparent" size="60" maxlength="60" placeholder="empresa" value="<?=$_POST['empresa']?>">
                <label>Empresa</label>
            </div>
            <div class="label-float mt-4">    
                <input type="text" name="apartamento" class="form-control mt-1 bg-transparent" size="60" maxlength="5" placeholder="Apartamento" value="<?=$_POST['apartamento']?>">
                <label>Apartamento</label>
            </div>
            <label class="mt-4 text-secondary">Bloco</label>
            <select class="form-control mt-0 pt-0" name="bloco" style="border-bottom: 2px solid #20B2AA!important;">
                <option value="<?=$_POST['bloco']?>"><?=$_POST['bloco']?></option>
                <?php if($_POST['bloco'] == 'A'){?>
                    <option value="B">B</option>
                <?php } else {?>
                    <option value="A">A</option>
                <?php }?>
            </select>
            <button type="submit" class="btn btn-register text-white w-100 mt-4">Atualizar</button>   
            <a href="/orders" class="btn btn-danger text-white w-100 mt-2">Voltar</a>      
        </form>
    </div>
</div>