<div class="nav navbar align-items-center bg-dark" style="height:8vh">
    <h5 class="m-0 text-light">Excluir cadastro</h5>
</div>

<div class="d-flex align-items-center justify-content-center px-1" style="height:92vh"> 
    <div class="py-4 px-3 card" style="width:30rem">
        <div class="d-flex justify-content-between">
            <h5 class="text-dark font-weight-bold">Empresa</h5>
            <h5 class="text-secondary font-weight-bold"><?=$_POST['empresa']?></h5>
        </div>
        <div class="d-flex justify-content-between mt-4">
            <h5 class="text-dark font-weight-bold">Apartamento</h5>
            <h5 class="text-secondary font-weight-bold"><?=$_POST['apartamento']?></h5>
        </div>
        <div class="d-flex justify-content-between mt-4">
            <h5 class="text-dark font-weight-bold">Bloco</h5>
            <h5 class="text-secondary font-weight-bold"><?=$_POST['bloco']?></h5>
        </div>
        
        <button type="button" class="btn btn-register text-white w-100 mt-4" data-toggle="modal" data-target="#deleteModal">Excluir</button>   
        <a href="/orders" class="btn btn-danger text-white w-100 mt-2">Voltar</a>      
    </div>
</div>

<!-- Modal de exclusão-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header text-center align-items-center">
            <h4 class="modal-title font-weight-bold text-secondary">Excluir cadastro</h4>
            <button type="button" class="close border-0" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
      <div class="modal-body">
        Você tem certeza que deseja excluir esse registro?
      </div>
      <div class="modal-footer">
        <form action="delete_orders" method="post">
            <input type="hidden" name="id_encomenda" value="<?=$_POST['id_encomenda']?>">
            <button type="submit" class="btn btn-info" style="width:120px">Sim</button>
        </form>
        <button type="button" class="btn btn-danger" style="width:120px" data-dismiss="modal">Não</button>
      </div>
    </div>
  </div>
</div>