<html lang="pt-BR">
<head>
	<title>Access</title>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<meta name="author" content="Guilherme Avelino, José Alisson" />

	<link rel="stylesheet" href="lib/bootstrap/css/bootstrap.min.css" />
	<link rel="stylesheet" href="lib/fontawesome/css/all.min.css">
	<link rel="stylesheet" href="lib/datatables/css/query.datatable.min.css" />
	<link rel="stylesheet" href="lib/datatables/css/responsive.datatable.min.css"/>
	<link rel="stylesheet" href="lib/datatables/css/dataTables.bootstrap4.min.css" />
	<link rel="stylesheet" href='lib/fullcalendar/core/main.min.css' />
	<link rel="stylesheet" href='lib/fullcalendar/daygrid/main.min.css' />
	<link rel="stylesheet" href='lib/fullcalendar/timegrid/main.min.css' />
	<link rel="stylesheet" href='lib/fullcalendar/list/main.min.css' />
	
	<link rel="stylesheet" href="css/all.css" />
	<link rel="stylesheet" href="css/content.css" />
	<link rel="stylesheet" href="css/header.css" />
	<link rel="stylesheet" href="css/dashboard.css" />
	<link rel="stylesheet" href="css/calendar.css" />
	<link rel="stylesheet" href="css/login-register.css" />
	<link rel="stylesheet" href="css/user_profile.css" />
</head>
<body onload="identifyBrowser()">
	<?= $this->content() ?>

	<script src="lib/datatables/js/popper.js"></script>
	<script src="lib/datatables/js/query-3.5.1.js"></script>
	<script src="lib/datatables/js/jquery.dataTables.min.js"></script>
	<script src="lib/datatables/js/datatable.responsive.js"></script>
	<script src="lib/datatables/js/dataTables.bootstrap4.min.js"></script>
	<script src="lib/datatables/js/datatable.js"></script>
	<script src="lib/bootstrap/js/bootstrap.min.js"></script>
	<script src="lib/jquery/jquery.mask.min.js"></script>

	<script src="js/not-supported.js"></script>
	<script src="js/mask-rg.js"></script>
	<script src="js/validation.js"></script>
	<script src="js/menu-user.js"></script>

	<script>
		$("#cpf").mask("999.999.999-99");
		$("#cad-cpf").mask("999.999.999-99");
		$("#rg").mask("99.999.999-9");
		$("#cad-rg").mask("99.999.999-9");
		$("#telefone").mask("(99) 9999-99999");
		$("#data_nascimento").mask("99/99/9999");
	</script>
</body>
</html>