<html>
	<head>
		<title>Access</title>
		<meta charset="utf-8"/>
   		<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<meta name="keywords" content=""/>
		<meta name="description" content=""/>
		<meta name="author" content="Guilherme Avelino, José Alisson"/>
 			
		<link rel="stylesheet" href="lib/bootstrap/css/bootstrap.min.css"/>
		<link rel="stylesheet" href="lib/fontawesome/css/all.min.css">
		<link rel="stylesheet" href="lib/datatables/css/dataTables.bootstrap4.min.css"/>
		<link rel="stylesheet" href="css/all.css"/>
		<link rel="stylesheet" href="css/content.css"/>
		<link rel="stylesheet" href="css/dashboard.css"/>
		<link rel="stylesheet" href="css/header.css"/>
		<link rel="stylesheet" href="css/login-register.css"/>
	</head>

	<body>
		<?= $this->content() ?>	
		
		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
		
		<script src="lib/bootstrap/js/bootstrap.min.js"></script>
		<script src="lib/jquery/jquery.mask.min.js"></script>
		<script src="lib/datatables/js/jquery.dataTables.min.js"></script>
		<script src="lib/datatables/js/dataTables.bootstrap4.min.js"></script>
		<script src="lib/datatables/js/datatable.js"></script>
		<script src="js/menu-user.js"></script>

		<script>
			$("#cpf").mask("000.000.000-00");
			$("#telefone").mask("(00) 0000-00000");
		</script>
	</body>
</html>